// This file is auto-generated by @hey-api/openapi-ts

export const BalancingSchemaSchema = {
  properties: {
    balance_current_a: {
      type: "number",
      title: "Balance Current A",
      description: "Balancer current in amperes.",
    },
    balancing_cells: {
      items: {
        type: "integer",
      },
      type: "array",
      title: "Balancing Cells",
      description: "1-based numbers of the cells currently being balanced.",
    },
    mosfet_temperature_c: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Mosfet Temperature C",
      description: "Balancer MOSFET temperature in °C.",
    },
    board_temperature_c: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Board Temperature C",
      description: "Balancer board temperature in °C.",
    },
  },
  type: "object",
  required: ["balance_current_a", "balancing_cells"],
  title: "BalancingSchema",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HistoryPeriodSchema = {
  type: "string",
  enum: ["5m", "1h"],
  title: "HistoryPeriod",
} as const;

export const PaginationSchema = {
  properties: {
    total_count: {
      type: "integer",
      title: "Total Count",
    },
    max_page: {
      type: "integer",
      title: "Max Page",
    },
  },
  type: "object",
  required: ["total_count", "max_page"],
  title: "Pagination",
} as const;

export const ReadingListResponseSchema = {
  properties: {
    items: {
      items: {
        $ref: "#/components/schemas/ReadingSchema",
      },
      type: "array",
      title: "Items",
    },
    pagination: {
      $ref: "#/components/schemas/Pagination",
    },
  },
  type: "object",
  required: ["items", "pagination"],
  title: "ReadingListResponse",
} as const;

export const ReadingSchemaSchema = {
  properties: {
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation timestamp of the object.",
    },
    modified_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Modified At",
      description: "Last modification timestamp of the object.",
    },
    id: {
      type: "string",
      format: "uuid4",
      title: "Id",
      description: "The ID of the object.",
    },
    device_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Device Name",
      description: "Bluetooth name of the BMS device.",
    },
    device_address: {
      type: "string",
      title: "Device Address",
      description: "Bluetooth address of the BMS device.",
    },
    device_model: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Device Model",
      description: "BMS model string reported by the device.",
    },
    protocol: {
      type: "string",
      title: "Protocol",
      description: "Protocol used to read the BMS.",
    },
    voltage_v: {
      type: "number",
      title: "Voltage V",
      description: "Total pack voltage in volts.",
    },
    current_a: {
      type: "number",
      title: "Current A",
      description:
        "Pack current in amperes; positive when charging, negative when discharging.",
    },
    power_w: {
      type: "number",
      title: "Power W",
      description: "Pack power in watts.",
    },
    soc_percent: {
      type: "number",
      title: "Soc Percent",
      description: "State of charge in percent.",
    },
    remaining_capacity_ah: {
      type: "number",
      title: "Remaining Capacity Ah",
      description: "Remaining capacity in ampere-hours.",
    },
    rated_capacity_ah: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Rated Capacity Ah",
      description: "Rated capacity in ampere-hours, from the BMS settings.",
    },
    mode: {
      type: "string",
      title: "Mode",
      description: "Pack mode: idle, charging or discharging.",
    },
    cycles: {
      type: "integer",
      title: "Cycles",
      description: "Charge cycle count.",
    },
    cell_count: {
      type: "integer",
      title: "Cell Count",
      description: "Number of cells in the pack.",
    },
    cell_voltage_max_v: {
      type: "number",
      title: "Cell Voltage Max V",
      description: "Highest cell voltage in volts.",
    },
    cell_voltage_min_v: {
      type: "number",
      title: "Cell Voltage Min V",
      description: "Lowest cell voltage in volts.",
    },
    cell_voltage_avg_v: {
      type: "number",
      title: "Cell Voltage Avg V",
      description: "Average cell voltage in volts.",
    },
    cell_voltage_delta_v: {
      type: "number",
      title: "Cell Voltage Delta V",
      description:
        "Difference between highest and lowest cell voltage in volts.",
    },
    temperature_sensor_count: {
      type: "integer",
      title: "Temperature Sensor Count",
      description: "Number of temperature sensors.",
    },
    temperature_max_c: {
      type: "number",
      title: "Temperature Max C",
      description: "Highest sensor temperature in °C.",
    },
    temperature_min_c: {
      type: "number",
      title: "Temperature Min C",
      description: "Lowest sensor temperature in °C.",
    },
    balancer_active: {
      type: "boolean",
      title: "Balancer Active",
      description: "Whether the balancer is active.",
    },
    charging_mosfet: {
      type: "boolean",
      title: "Charging Mosfet",
      description: "Whether the charging MOSFET is enabled.",
    },
    discharging_mosfet: {
      type: "boolean",
      title: "Discharging Mosfet",
      description: "Whether the discharging MOSFET is enabled.",
    },
    has_alarms: {
      type: "boolean",
      title: "Has Alarms",
      description: "Whether any alarm register is set.",
    },
    cell_voltages: {
      items: {
        type: "number",
      },
      type: "array",
      title: "Cell Voltages",
      description: "Per-cell voltages in volts, ordered by cell number.",
    },
    temperatures: {
      items: {
        type: "number",
      },
      type: "array",
      title: "Temperatures",
      description: "Per-sensor temperatures in °C, ordered by sensor number.",
    },
    balancing: {
      anyOf: [
        {
          $ref: "#/components/schemas/BalancingSchema",
        },
        {
          type: "null",
        },
      ],
      description: "Balancing details, if reported by the BMS.",
    },
    alarms: {
      anyOf: [
        {
          additionalProperties: {
            type: "string",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Alarms",
      description:
        "Raw alarm registers as hex strings, or null when no alarms are set.",
    },
    alarm_messages: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Alarm Messages",
      description:
        "Human-readable alarm/warning messages decoded from the alarm registers.",
    },
  },
  type: "object",
  required: [
    "created_at",
    "modified_at",
    "id",
    "device_name",
    "device_address",
    "device_model",
    "protocol",
    "voltage_v",
    "current_a",
    "power_w",
    "soc_percent",
    "remaining_capacity_ah",
    "rated_capacity_ah",
    "mode",
    "cycles",
    "cell_count",
    "cell_voltage_max_v",
    "cell_voltage_min_v",
    "cell_voltage_avg_v",
    "cell_voltage_delta_v",
    "temperature_sensor_count",
    "temperature_max_c",
    "temperature_min_c",
    "balancer_active",
    "charging_mosfet",
    "discharging_mosfet",
    "has_alarms",
    "cell_voltages",
    "temperatures",
    "balancing",
    "alarms",
    "alarm_messages",
  ],
  title: "ReadingSchema",
} as const;

export const ReadingSortPropertySchema = {
  type: "string",
  enum: [
    "created_at",
    "-created_at",
    "voltage_v",
    "-voltage_v",
    "soc_percent",
    "-soc_percent",
  ],
  title: "ReadingSortProperty",
} as const;

export const RruleFrequencySchema = {
  type: "string",
  enum: ["daily", "weekly", "monthly", "yearly"],
  title: "RruleFrequency",
} as const;

export const SocHistoryBucketSchemaSchema = {
  properties: {
    bucket_start: {
      type: "string",
      format: "date-time",
      title: "Bucket Start",
      description: "Start of this bucket, UTC.",
    },
    soc_percent: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Soc Percent",
      description:
        "Average state of charge in this bucket, or the last known value carried forward when the bucket has no readings.",
    },
    has_data: {
      type: "boolean",
      title: "Has Data",
      description: "Whether a reading actually fell in this bucket.",
    },
  },
  type: "object",
  required: ["bucket_start", "soc_percent", "has_data"],
  title: "SocHistoryBucketSchema",
} as const;

export const SocHistoryResponseSchema = {
  properties: {
    buckets: {
      items: {
        $ref: "#/components/schemas/SocHistoryBucketSchema",
      },
      type: "array",
      title: "Buckets",
      description: "The most recent 30 buckets, oldest first.",
    },
  },
  type: "object",
  required: ["buckets"],
  title: "SocHistoryResponse",
} as const;

export const TaskCompleteResponseSchema = {
  properties: {
    completed_task: {
      $ref: "#/components/schemas/TaskSchema",
    },
    next_task: {
      anyOf: [
        {
          $ref: "#/components/schemas/TaskSchema",
        },
        {
          type: "null",
        },
      ],
      description: "Next recurring instance, if applicable.",
    },
  },
  type: "object",
  required: ["completed_task"],
  title: "TaskCompleteResponse",
} as const;

export const TaskCreateSchema = {
  properties: {
    title: {
      type: "string",
      maxLength: 500,
      title: "Title",
      description: "Task title.",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    status: {
      $ref: "#/components/schemas/TaskStatus",
      default: "todo",
    },
    priority: {
      type: "integer",
      maximum: 4,
      minimum: 0,
      title: "Priority",
      default: 0,
    },
    due_date: {
      anyOf: [
        {
          type: "string",
          format: "date",
        },
        {
          type: "null",
        },
      ],
      title: "Due Date",
    },
    area: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
        },
        {
          type: "null",
        },
      ],
      title: "Area",
    },
    tags: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Tags",
    },
    position: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Position",
    },
    is_recurring: {
      type: "boolean",
      title: "Is Recurring",
      default: false,
    },
    rrule_frequency: {
      anyOf: [
        {
          $ref: "#/components/schemas/RruleFrequency",
        },
        {
          type: "null",
        },
      ],
    },
    rrule_interval: {
      anyOf: [
        {
          type: "integer",
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Interval",
    },
    rrule_day_of_week: {
      anyOf: [
        {
          type: "integer",
          maximum: 6,
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Day Of Week",
    },
    rrule_day_of_month: {
      anyOf: [
        {
          type: "integer",
          maximum: 31,
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Day Of Month",
    },
  },
  type: "object",
  required: ["title"],
  title: "TaskCreate",
} as const;

export const TaskListResponseSchema = {
  properties: {
    items: {
      items: {
        $ref: "#/components/schemas/TaskSchema",
      },
      type: "array",
      title: "Items",
    },
    pagination: {
      $ref: "#/components/schemas/Pagination",
    },
  },
  type: "object",
  required: ["items", "pagination"],
  title: "TaskListResponse",
} as const;

export const TaskReorderItemSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    position: {
      type: "number",
      title: "Position",
    },
    status: {
      anyOf: [
        {
          $ref: "#/components/schemas/TaskStatus",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: ["id", "position"],
  title: "TaskReorderItem",
} as const;

export const TaskSchemaSchema = {
  properties: {
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation timestamp of the object.",
    },
    modified_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Modified At",
      description: "Last modification timestamp of the object.",
    },
    id: {
      type: "string",
      format: "uuid4",
      title: "Id",
      description: "The ID of the object.",
    },
    title: {
      type: "string",
      title: "Title",
      description: "Task title.",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Task description.",
    },
    status: {
      $ref: "#/components/schemas/TaskStatus",
      description: "Task status.",
      default: "todo",
    },
    priority: {
      type: "integer",
      title: "Priority",
      description: "Priority (0=none, 1=low, 2=medium, 3=high, 4=urgent).",
      default: 0,
    },
    due_date: {
      anyOf: [
        {
          type: "string",
          format: "date",
        },
        {
          type: "null",
        },
      ],
      title: "Due Date",
      description: "Due date.",
    },
    completed_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Completed At",
      description: "Completion timestamp.",
    },
    area: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Area",
      description: "Area (e.g. Company, Personal, Travel).",
    },
    tags: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Tags",
      description: "User-defined tags.",
    },
    position: {
      type: "number",
      title: "Position",
      description: "Position for ordering within a status column.",
      default: 0,
    },
    is_recurring: {
      type: "boolean",
      title: "Is Recurring",
      description: "Whether this task recurs.",
      default: false,
    },
    rrule_frequency: {
      anyOf: [
        {
          $ref: "#/components/schemas/RruleFrequency",
        },
        {
          type: "null",
        },
      ],
      description: "Recurrence frequency.",
    },
    rrule_interval: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Interval",
      description: "Recurrence interval.",
    },
    rrule_day_of_week: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Day Of Week",
      description: "Day of week for weekly recurrence (0=Mon, 6=Sun).",
    },
    rrule_day_of_month: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Day Of Month",
      description: "Day of month for monthly recurrence (1-31).",
    },
    parent_task_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Task Id",
      description: "Parent task ID for recurring chain.",
    },
  },
  type: "object",
  required: ["created_at", "modified_at", "id", "title"],
  title: "TaskSchema",
} as const;

export const TaskSortPropertySchema = {
  type: "string",
  enum: [
    "created_at",
    "-created_at",
    "due_date",
    "-due_date",
    "priority",
    "-priority",
    "title",
    "-title",
    "completed_at",
    "-completed_at",
    "position",
    "-position",
  ],
  title: "TaskSortProperty",
} as const;

export const TaskStatusSchema = {
  type: "string",
  enum: ["todo", "in_progress", "done", "cancelled"],
  title: "TaskStatus",
} as const;

export const TaskUpdateSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: "string",
          maxLength: 500,
        },
        {
          type: "null",
        },
      ],
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    status: {
      anyOf: [
        {
          $ref: "#/components/schemas/TaskStatus",
        },
        {
          type: "null",
        },
      ],
    },
    priority: {
      anyOf: [
        {
          type: "integer",
          maximum: 4,
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Priority",
    },
    due_date: {
      anyOf: [
        {
          type: "string",
          format: "date",
        },
        {
          type: "null",
        },
      ],
      title: "Due Date",
    },
    area: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
        },
        {
          type: "null",
        },
      ],
      title: "Area",
    },
    tags: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Tags",
    },
    position: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Position",
    },
    is_recurring: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Recurring",
    },
    rrule_frequency: {
      anyOf: [
        {
          $ref: "#/components/schemas/RruleFrequency",
        },
        {
          type: "null",
        },
      ],
    },
    rrule_interval: {
      anyOf: [
        {
          type: "integer",
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Interval",
    },
    rrule_day_of_week: {
      anyOf: [
        {
          type: "integer",
          maximum: 6,
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Day Of Week",
    },
    rrule_day_of_month: {
      anyOf: [
        {
          type: "integer",
          maximum: 31,
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Rrule Day Of Month",
    },
  },
  type: "object",
  title: "TaskUpdate",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
