// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.js";
import {
  completeTaskV1TasksTaskIdCompletePostResponseTransformer,
  createReadingV1ReadingsPostResponseTransformer,
  createTaskV1TasksPostResponseTransformer,
  getLatestReadingV1ReadingsLatestGetResponseTransformer,
  getReadingV1ReadingsReadingIdGetResponseTransformer,
  getSocHistoryV1ReadingsSocHistoryGetResponseTransformer,
  getTaskV1TasksTaskIdGetResponseTransformer,
  listReadingsV1ReadingsGetResponseTransformer,
  listTasksV1TasksGetResponseTransformer,
  reopenTaskV1TasksTaskIdReopenPostResponseTransformer,
  updateTaskV1TasksTaskIdPatchResponseTransformer,
} from "./transformers.gen.js";
import type {
  CompleteTaskV1TasksTaskIdCompletePostData,
  CompleteTaskV1TasksTaskIdCompletePostErrors,
  CompleteTaskV1TasksTaskIdCompletePostResponses,
  CreateReadingV1ReadingsPostData,
  CreateReadingV1ReadingsPostResponses,
  CreateTaskV1TasksPostData,
  CreateTaskV1TasksPostErrors,
  CreateTaskV1TasksPostResponses,
  DeleteTaskV1TasksTaskIdDeleteData,
  DeleteTaskV1TasksTaskIdDeleteErrors,
  DeleteTaskV1TasksTaskIdDeleteResponses,
  GetLatestReadingV1ReadingsLatestGetData,
  GetLatestReadingV1ReadingsLatestGetResponses,
  GetReadingV1ReadingsReadingIdGetData,
  GetReadingV1ReadingsReadingIdGetErrors,
  GetReadingV1ReadingsReadingIdGetResponses,
  GetSocHistoryV1ReadingsSocHistoryGetData,
  GetSocHistoryV1ReadingsSocHistoryGetErrors,
  GetSocHistoryV1ReadingsSocHistoryGetResponses,
  GetTaskV1TasksTaskIdGetData,
  GetTaskV1TasksTaskIdGetErrors,
  GetTaskV1TasksTaskIdGetResponses,
  HealthzHealthzGetData,
  HealthzHealthzGetResponses,
  ListAreasV1TasksAreasGetData,
  ListAreasV1TasksAreasGetResponses,
  ListReadingsV1ReadingsGetData,
  ListReadingsV1ReadingsGetErrors,
  ListReadingsV1ReadingsGetResponses,
  ListTasksV1TasksGetData,
  ListTasksV1TasksGetErrors,
  ListTasksV1TasksGetResponses,
  ReopenTaskV1TasksTaskIdReopenPostData,
  ReopenTaskV1TasksTaskIdReopenPostErrors,
  ReopenTaskV1TasksTaskIdReopenPostResponses,
  ReorderTasksV1TasksReorderPatchData,
  ReorderTasksV1TasksReorderPatchErrors,
  ReorderTasksV1TasksReorderPatchResponses,
  UpdateTaskV1TasksTaskIdPatchData,
  UpdateTaskV1TasksTaskIdPatchErrors,
  UpdateTaskV1TasksTaskIdPatchResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Healthz
 */
export const healthzHealthzGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthzHealthzGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthzHealthzGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/healthz", ...options });

/**
 * List Tasks
 */
export const listTasksV1TasksGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListTasksV1TasksGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTasksV1TasksGetResponses,
    ListTasksV1TasksGetErrors,
    ThrowOnError
  >({
    responseTransformer: listTasksV1TasksGetResponseTransformer,
    url: "/v1/tasks",
    ...options,
  });

/**
 * Create Task
 */
export const createTaskV1TasksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTaskV1TasksPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateTaskV1TasksPostResponses,
    CreateTaskV1TasksPostErrors,
    ThrowOnError
  >({
    responseTransformer: createTaskV1TasksPostResponseTransformer,
    url: "/v1/tasks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reorder Tasks
 */
export const reorderTasksV1TasksReorderPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReorderTasksV1TasksReorderPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    ReorderTasksV1TasksReorderPatchResponses,
    ReorderTasksV1TasksReorderPatchErrors,
    ThrowOnError
  >({
    url: "/v1/tasks/reorder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Task
 */
export const deleteTaskV1TasksTaskIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTaskV1TasksTaskIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTaskV1TasksTaskIdDeleteResponses,
    DeleteTaskV1TasksTaskIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/tasks/{task_id}", ...options });

/**
 * Get Task
 */
export const getTaskV1TasksTaskIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskV1TasksTaskIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTaskV1TasksTaskIdGetResponses,
    GetTaskV1TasksTaskIdGetErrors,
    ThrowOnError
  >({
    responseTransformer: getTaskV1TasksTaskIdGetResponseTransformer,
    url: "/v1/tasks/{task_id}",
    ...options,
  });

/**
 * Update Task
 */
export const updateTaskV1TasksTaskIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTaskV1TasksTaskIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateTaskV1TasksTaskIdPatchResponses,
    UpdateTaskV1TasksTaskIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer: updateTaskV1TasksTaskIdPatchResponseTransformer,
    url: "/v1/tasks/{task_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Complete Task
 */
export const completeTaskV1TasksTaskIdCompletePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompleteTaskV1TasksTaskIdCompletePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CompleteTaskV1TasksTaskIdCompletePostResponses,
    CompleteTaskV1TasksTaskIdCompletePostErrors,
    ThrowOnError
  >({
    responseTransformer:
      completeTaskV1TasksTaskIdCompletePostResponseTransformer,
    url: "/v1/tasks/{task_id}/complete",
    ...options,
  });

/**
 * Reopen Task
 */
export const reopenTaskV1TasksTaskIdReopenPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReopenTaskV1TasksTaskIdReopenPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ReopenTaskV1TasksTaskIdReopenPostResponses,
    ReopenTaskV1TasksTaskIdReopenPostErrors,
    ThrowOnError
  >({
    responseTransformer: reopenTaskV1TasksTaskIdReopenPostResponseTransformer,
    url: "/v1/tasks/{task_id}/reopen",
    ...options,
  });

/**
 * List Areas
 */
export const listAreasV1TasksAreasGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListAreasV1TasksAreasGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListAreasV1TasksAreasGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/tasks/areas", ...options });

/**
 * List Readings
 */
export const listReadingsV1ReadingsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListReadingsV1ReadingsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListReadingsV1ReadingsGetResponses,
    ListReadingsV1ReadingsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listReadingsV1ReadingsGetResponseTransformer,
    url: "/v1/readings",
    ...options,
  });

/**
 * Capture Reading
 */
export const createReadingV1ReadingsPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CreateReadingV1ReadingsPostData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    CreateReadingV1ReadingsPostResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: createReadingV1ReadingsPostResponseTransformer,
    url: "/v1/readings",
    ...options,
  });

/**
 * Get Latest Reading
 */
export const getLatestReadingV1ReadingsLatestGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetLatestReadingV1ReadingsLatestGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetLatestReadingV1ReadingsLatestGetResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getLatestReadingV1ReadingsLatestGetResponseTransformer,
    url: "/v1/readings/latest",
    ...options,
  });

/**
 * Get SOC History
 */
export const getSocHistoryV1ReadingsSocHistoryGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetSocHistoryV1ReadingsSocHistoryGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSocHistoryV1ReadingsSocHistoryGetResponses,
    GetSocHistoryV1ReadingsSocHistoryGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getSocHistoryV1ReadingsSocHistoryGetResponseTransformer,
    url: "/v1/readings/soc-history",
    ...options,
  });

/**
 * Get Reading
 */
export const getReadingV1ReadingsReadingIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetReadingV1ReadingsReadingIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetReadingV1ReadingsReadingIdGetResponses,
    GetReadingV1ReadingsReadingIdGetErrors,
    ThrowOnError
  >({
    responseTransformer: getReadingV1ReadingsReadingIdGetResponseTransformer,
    url: "/v1/readings/{reading_id}",
    ...options,
  });
