// This file is auto-generated by @hey-api/openapi-ts

import type {
  CompleteTaskV1TasksTaskIdCompletePostResponse,
  CreateReadingV1ReadingsPostResponse,
  CreateTaskV1TasksPostResponse,
  GetLatestReadingV1ReadingsLatestGetResponse,
  GetReadingV1ReadingsReadingIdGetResponse,
  GetTaskV1TasksTaskIdGetResponse,
  ListReadingsV1ReadingsGetResponse,
  ListTasksV1TasksGetResponse,
  ReopenTaskV1TasksTaskIdReopenPostResponse,
  UpdateTaskV1TasksTaskIdPatchResponse,
} from "./types.gen.js";

const taskSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.due_date) {
    data.due_date = new Date(data.due_date);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  return data;
};

const taskListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    taskSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listTasksV1TasksGetResponseTransformer = async (
  data: any,
): Promise<ListTasksV1TasksGetResponse> => {
  data = taskListResponseSchemaResponseTransformer(data);
  return data;
};

export const createTaskV1TasksPostResponseTransformer = async (
  data: any,
): Promise<CreateTaskV1TasksPostResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

export const getTaskV1TasksTaskIdGetResponseTransformer = async (
  data: any,
): Promise<GetTaskV1TasksTaskIdGetResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateTaskV1TasksTaskIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateTaskV1TasksTaskIdPatchResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

const taskCompleteResponseSchemaResponseTransformer = (data: any) => {
  data.completed_task = taskSchemaSchemaResponseTransformer(
    data.completed_task,
  );
  if (data.next_task) {
    data.next_task = taskSchemaSchemaResponseTransformer(data.next_task);
  }
  return data;
};

export const completeTaskV1TasksTaskIdCompletePostResponseTransformer = async (
  data: any,
): Promise<CompleteTaskV1TasksTaskIdCompletePostResponse> => {
  data = taskCompleteResponseSchemaResponseTransformer(data);
  return data;
};

export const reopenTaskV1TasksTaskIdReopenPostResponseTransformer = async (
  data: any,
): Promise<ReopenTaskV1TasksTaskIdReopenPostResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

const readingSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const readingListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    readingSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listReadingsV1ReadingsGetResponseTransformer = async (
  data: any,
): Promise<ListReadingsV1ReadingsGetResponse> => {
  data = readingListResponseSchemaResponseTransformer(data);
  return data;
};

export const createReadingV1ReadingsPostResponseTransformer = async (
  data: any,
): Promise<CreateReadingV1ReadingsPostResponse> => {
  data = readingSchemaSchemaResponseTransformer(data);
  return data;
};

export const getLatestReadingV1ReadingsLatestGetResponseTransformer = async (
  data: any,
): Promise<GetLatestReadingV1ReadingsLatestGetResponse> => {
  data = readingSchemaSchemaResponseTransformer(data);
  return data;
};

export const getReadingV1ReadingsReadingIdGetResponseTransformer = async (
  data: any,
): Promise<GetReadingV1ReadingsReadingIdGetResponse> => {
  data = readingSchemaSchemaResponseTransformer(data);
  return data;
};
