// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.getbessel.com" | (string & {});
};

/**
 * BalancingSchema
 */
export type BalancingSchema = {
  /**
   * Balance Current A
   *
   * Balancer current in amperes.
   */
  balance_current_a: number;
  /**
   * Balancing Cells
   *
   * 1-based numbers of the cells currently being balanced.
   */
  balancing_cells: Array<number>;
  /**
   * Mosfet Temperature C
   *
   * Balancer MOSFET temperature in °C.
   */
  mosfet_temperature_c?: number | null;
  /**
   * Board Temperature C
   *
   * Balancer board temperature in °C.
   */
  board_temperature_c?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HistoryPeriod
 */
export const HistoryPeriod = { "5M": "5m", "1H": "1h" } as const;

/**
 * HistoryPeriod
 */
export type HistoryPeriod = (typeof HistoryPeriod)[keyof typeof HistoryPeriod];

/**
 * Pagination
 */
export type Pagination = {
  /**
   * Total Count
   */
  total_count: number;
  /**
   * Max Page
   */
  max_page: number;
};

/**
 * ReadingListResponse
 */
export type ReadingListResponse = {
  /**
   * Items
   */
  items: Array<ReadingSchema>;
  pagination: Pagination;
};

/**
 * ReadingSchema
 */
export type ReadingSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Device Name
   *
   * Bluetooth name of the BMS device.
   */
  device_name: string | null;
  /**
   * Device Address
   *
   * Bluetooth address of the BMS device.
   */
  device_address: string;
  /**
   * Device Model
   *
   * BMS model string reported by the device.
   */
  device_model: string | null;
  /**
   * Protocol
   *
   * Protocol used to read the BMS.
   */
  protocol: string;
  /**
   * Voltage V
   *
   * Total pack voltage in volts.
   */
  voltage_v: number;
  /**
   * Current A
   *
   * Pack current in amperes; positive when charging, negative when discharging.
   */
  current_a: number;
  /**
   * Power W
   *
   * Pack power in watts.
   */
  power_w: number;
  /**
   * Soc Percent
   *
   * State of charge in percent.
   */
  soc_percent: number;
  /**
   * Remaining Capacity Ah
   *
   * Remaining capacity in ampere-hours.
   */
  remaining_capacity_ah: number;
  /**
   * Rated Capacity Ah
   *
   * Rated capacity in ampere-hours, from the BMS settings.
   */
  rated_capacity_ah: number | null;
  /**
   * Mode
   *
   * Pack mode: idle, charging or discharging.
   */
  mode: string;
  /**
   * Cycles
   *
   * Charge cycle count.
   */
  cycles: number;
  /**
   * Cell Count
   *
   * Number of cells in the pack.
   */
  cell_count: number;
  /**
   * Cell Voltage Max V
   *
   * Highest cell voltage in volts.
   */
  cell_voltage_max_v: number;
  /**
   * Cell Voltage Min V
   *
   * Lowest cell voltage in volts.
   */
  cell_voltage_min_v: number;
  /**
   * Cell Voltage Avg V
   *
   * Average cell voltage in volts.
   */
  cell_voltage_avg_v: number;
  /**
   * Cell Voltage Delta V
   *
   * Difference between highest and lowest cell voltage in volts.
   */
  cell_voltage_delta_v: number;
  /**
   * Temperature Sensor Count
   *
   * Number of temperature sensors.
   */
  temperature_sensor_count: number;
  /**
   * Temperature Max C
   *
   * Highest sensor temperature in °C.
   */
  temperature_max_c: number;
  /**
   * Temperature Min C
   *
   * Lowest sensor temperature in °C.
   */
  temperature_min_c: number;
  /**
   * Balancer Active
   *
   * Whether the balancer is active.
   */
  balancer_active: boolean;
  /**
   * Charging Mosfet
   *
   * Whether the charging MOSFET is enabled.
   */
  charging_mosfet: boolean;
  /**
   * Discharging Mosfet
   *
   * Whether the discharging MOSFET is enabled.
   */
  discharging_mosfet: boolean;
  /**
   * Has Alarms
   *
   * Whether any alarm register is set.
   */
  has_alarms: boolean;
  /**
   * Cell Voltages
   *
   * Per-cell voltages in volts, ordered by cell number.
   */
  cell_voltages: Array<number>;
  /**
   * Temperatures
   *
   * Per-sensor temperatures in °C, ordered by sensor number.
   */
  temperatures: Array<number>;
  /**
   * Balancing details, if reported by the BMS.
   */
  balancing: BalancingSchema | null;
  /**
   * Alarms
   *
   * Raw alarm registers as hex strings, or null when no alarms are set.
   */
  alarms: {
    [key: string]: string;
  } | null;
  /**
   * Alarm Messages
   *
   * Human-readable alarm/warning messages decoded from the alarm registers.
   */
  alarm_messages: Array<string> | null;
};

/**
 * ReadingSortProperty
 */
export const ReadingSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  VOLTAGE_V: "voltage_v",
  "-VOLTAGE_V": "-voltage_v",
  SOC_PERCENT: "soc_percent",
  "-SOC_PERCENT": "-soc_percent",
} as const;

/**
 * ReadingSortProperty
 */
export type ReadingSortProperty =
  (typeof ReadingSortProperty)[keyof typeof ReadingSortProperty];

/**
 * RruleFrequency
 */
export const RruleFrequency = {
  DAILY: "daily",
  WEEKLY: "weekly",
  MONTHLY: "monthly",
  YEARLY: "yearly",
} as const;

/**
 * RruleFrequency
 */
export type RruleFrequency =
  (typeof RruleFrequency)[keyof typeof RruleFrequency];

/**
 * SocHistoryBucketSchema
 */
export type SocHistoryBucketSchema = {
  /**
   * Bucket Start
   *
   * Start of this bucket, UTC.
   */
  bucket_start: Date;
  /**
   * Soc Percent
   *
   * Average state of charge in this bucket, or the last known value carried forward when the bucket has no readings.
   */
  soc_percent: number | null;
  /**
   * Has Data
   *
   * Whether a reading actually fell in this bucket.
   */
  has_data: boolean;
};

/**
 * SocHistoryResponse
 */
export type SocHistoryResponse = {
  /**
   * Buckets
   *
   * The most recent 30 buckets, oldest first.
   */
  buckets: Array<SocHistoryBucketSchema>;
};

/**
 * TaskCompleteResponse
 */
export type TaskCompleteResponse = {
  completed_task: TaskSchema;
  /**
   * Next recurring instance, if applicable.
   */
  next_task?: TaskSchema | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
  /**
   * Title
   *
   * Task title.
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  status?: TaskStatus;
  /**
   * Priority
   */
  priority?: number;
  /**
   * Due Date
   */
  due_date?: Date | null;
  /**
   * Area
   */
  area?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Position
   */
  position?: number | null;
  /**
   * Is Recurring
   */
  is_recurring?: boolean;
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   */
  rrule_day_of_month?: number | null;
};

/**
 * TaskListResponse
 */
export type TaskListResponse = {
  /**
   * Items
   */
  items: Array<TaskSchema>;
  pagination: Pagination;
};

/**
 * TaskReorderItem
 */
export type TaskReorderItem = {
  /**
   * Id
   */
  id: string;
  /**
   * Position
   */
  position: number;
  status?: TaskStatus | null;
};

/**
 * TaskSchema
 */
export type TaskSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Title
   *
   * Task title.
   */
  title: string;
  /**
   * Description
   *
   * Task description.
   */
  description?: string | null;
  /**
   * Task status.
   */
  status?: TaskStatus;
  /**
   * Priority
   *
   * Priority (0=none, 1=low, 2=medium, 3=high, 4=urgent).
   */
  priority?: number;
  /**
   * Due Date
   *
   * Due date.
   */
  due_date?: Date | null;
  /**
   * Completed At
   *
   * Completion timestamp.
   */
  completed_at?: Date | null;
  /**
   * Area
   *
   * Area (e.g. Company, Personal, Travel).
   */
  area?: string | null;
  /**
   * Tags
   *
   * User-defined tags.
   */
  tags?: Array<string> | null;
  /**
   * Position
   *
   * Position for ordering within a status column.
   */
  position?: number;
  /**
   * Is Recurring
   *
   * Whether this task recurs.
   */
  is_recurring?: boolean;
  /**
   * Recurrence frequency.
   */
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   *
   * Recurrence interval.
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   *
   * Day of week for weekly recurrence (0=Mon, 6=Sun).
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   *
   * Day of month for monthly recurrence (1-31).
   */
  rrule_day_of_month?: number | null;
  /**
   * Parent Task Id
   *
   * Parent task ID for recurring chain.
   */
  parent_task_id?: string | null;
};

/**
 * TaskSortProperty
 */
export const TaskSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  DUE_DATE: "due_date",
  "-DUE_DATE": "-due_date",
  PRIORITY: "priority",
  "-PRIORITY": "-priority",
  TITLE: "title",
  "-TITLE": "-title",
  COMPLETED_AT: "completed_at",
  "-COMPLETED_AT": "-completed_at",
  POSITION: "position",
  "-POSITION": "-position",
} as const;

/**
 * TaskSortProperty
 */
export type TaskSortProperty =
  (typeof TaskSortProperty)[keyof typeof TaskSortProperty];

/**
 * TaskStatus
 */
export const TaskStatus = {
  TODO: "todo",
  IN_PROGRESS: "in_progress",
  DONE: "done",
  CANCELLED: "cancelled",
} as const;

/**
 * TaskStatus
 */
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

/**
 * TaskUpdate
 */
export type TaskUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  status?: TaskStatus | null;
  /**
   * Priority
   */
  priority?: number | null;
  /**
   * Due Date
   */
  due_date?: Date | null;
  /**
   * Area
   */
  area?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Position
   */
  position?: number | null;
  /**
   * Is Recurring
   */
  is_recurring?: boolean | null;
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   */
  rrule_day_of_month?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthzHealthzGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/healthz";
};

export type HealthzHealthzGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListTasksV1TasksGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     *
     * Filter by status. Repeat to filter by multiple.
     */
    status?: Array<TaskStatus> | null;
    /**
     * Priority
     *
     * Filter by priority.
     */
    priority?: number | null;
    /**
     * Area
     *
     * Filter by area.
     */
    area?: string | null;
    /**
     * Is Recurring
     *
     * Filter by recurring.
     */
    is_recurring?: boolean | null;
    /**
     * Completed After
     *
     * Filter tasks completed after this Unix timestamp (inclusive).
     */
    completed_after?: number | null;
    /**
     * Completed Before
     *
     * Filter tasks completed before this Unix timestamp (exclusive).
     */
    completed_before?: number | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<TaskSortProperty> | null;
  };
  url: "/v1/tasks";
};

export type ListTasksV1TasksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTasksV1TasksGetError =
  ListTasksV1TasksGetErrors[keyof ListTasksV1TasksGetErrors];

export type ListTasksV1TasksGetResponses = {
  /**
   * Successful Response
   */
  200: TaskListResponse;
};

export type ListTasksV1TasksGetResponse =
  ListTasksV1TasksGetResponses[keyof ListTasksV1TasksGetResponses];

export type CreateTaskV1TasksPostData = {
  body: TaskCreate;
  path?: never;
  query?: never;
  url: "/v1/tasks";
};

export type CreateTaskV1TasksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTaskV1TasksPostError =
  CreateTaskV1TasksPostErrors[keyof CreateTaskV1TasksPostErrors];

export type CreateTaskV1TasksPostResponses = {
  /**
   * Successful Response
   */
  201: TaskSchema;
};

export type CreateTaskV1TasksPostResponse =
  CreateTaskV1TasksPostResponses[keyof CreateTaskV1TasksPostResponses];

export type ReorderTasksV1TasksReorderPatchData = {
  /**
   * Body
   */
  body: Array<TaskReorderItem>;
  path?: never;
  query?: never;
  url: "/v1/tasks/reorder";
};

export type ReorderTasksV1TasksReorderPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReorderTasksV1TasksReorderPatchError =
  ReorderTasksV1TasksReorderPatchErrors[keyof ReorderTasksV1TasksReorderPatchErrors];

export type ReorderTasksV1TasksReorderPatchResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ReorderTasksV1TasksReorderPatchResponse =
  ReorderTasksV1TasksReorderPatchResponses[keyof ReorderTasksV1TasksReorderPatchResponses];

export type DeleteTaskV1TasksTaskIdDeleteData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type DeleteTaskV1TasksTaskIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTaskV1TasksTaskIdDeleteError =
  DeleteTaskV1TasksTaskIdDeleteErrors[keyof DeleteTaskV1TasksTaskIdDeleteErrors];

export type DeleteTaskV1TasksTaskIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTaskV1TasksTaskIdDeleteResponse =
  DeleteTaskV1TasksTaskIdDeleteResponses[keyof DeleteTaskV1TasksTaskIdDeleteResponses];

export type GetTaskV1TasksTaskIdGetData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type GetTaskV1TasksTaskIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTaskV1TasksTaskIdGetError =
  GetTaskV1TasksTaskIdGetErrors[keyof GetTaskV1TasksTaskIdGetErrors];

export type GetTaskV1TasksTaskIdGetResponses = {
  /**
   * Successful Response
   */
  200: TaskSchema;
};

export type GetTaskV1TasksTaskIdGetResponse =
  GetTaskV1TasksTaskIdGetResponses[keyof GetTaskV1TasksTaskIdGetResponses];

export type UpdateTaskV1TasksTaskIdPatchData = {
  body: TaskUpdate;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type UpdateTaskV1TasksTaskIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTaskV1TasksTaskIdPatchError =
  UpdateTaskV1TasksTaskIdPatchErrors[keyof UpdateTaskV1TasksTaskIdPatchErrors];

export type UpdateTaskV1TasksTaskIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TaskSchema;
};

export type UpdateTaskV1TasksTaskIdPatchResponse =
  UpdateTaskV1TasksTaskIdPatchResponses[keyof UpdateTaskV1TasksTaskIdPatchResponses];

export type CompleteTaskV1TasksTaskIdCompletePostData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/complete";
};

export type CompleteTaskV1TasksTaskIdCompletePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CompleteTaskV1TasksTaskIdCompletePostError =
  CompleteTaskV1TasksTaskIdCompletePostErrors[keyof CompleteTaskV1TasksTaskIdCompletePostErrors];

export type CompleteTaskV1TasksTaskIdCompletePostResponses = {
  /**
   * Successful Response
   */
  200: TaskCompleteResponse;
};

export type CompleteTaskV1TasksTaskIdCompletePostResponse =
  CompleteTaskV1TasksTaskIdCompletePostResponses[keyof CompleteTaskV1TasksTaskIdCompletePostResponses];

export type ReopenTaskV1TasksTaskIdReopenPostData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/reopen";
};

export type ReopenTaskV1TasksTaskIdReopenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReopenTaskV1TasksTaskIdReopenPostError =
  ReopenTaskV1TasksTaskIdReopenPostErrors[keyof ReopenTaskV1TasksTaskIdReopenPostErrors];

export type ReopenTaskV1TasksTaskIdReopenPostResponses = {
  /**
   * Successful Response
   */
  200: TaskSchema;
};

export type ReopenTaskV1TasksTaskIdReopenPostResponse =
  ReopenTaskV1TasksTaskIdReopenPostResponses[keyof ReopenTaskV1TasksTaskIdReopenPostResponses];

export type ListAreasV1TasksAreasGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/tasks/areas";
};

export type ListAreasV1TasksAreasGetResponses = {
  /**
   * Response List Areas V1 Tasks Areas Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ListAreasV1TasksAreasGetResponse =
  ListAreasV1TasksAreasGetResponses[keyof ListAreasV1TasksAreasGetResponses];

export type ListReadingsV1ReadingsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Created After
     *
     * Filter readings created after this Unix timestamp (inclusive).
     */
    created_after?: number | null;
    /**
     * Created Before
     *
     * Filter readings created before this Unix timestamp (exclusive).
     */
    created_before?: number | null;
    /**
     * Has Alarms
     *
     * Filter by alarm presence.
     */
    has_alarms?: boolean | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<ReadingSortProperty> | null;
  };
  url: "/v1/readings";
};

export type ListReadingsV1ReadingsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListReadingsV1ReadingsGetError =
  ListReadingsV1ReadingsGetErrors[keyof ListReadingsV1ReadingsGetErrors];

export type ListReadingsV1ReadingsGetResponses = {
  /**
   * Successful Response
   */
  200: ReadingListResponse;
};

export type ListReadingsV1ReadingsGetResponse =
  ListReadingsV1ReadingsGetResponses[keyof ListReadingsV1ReadingsGetResponses];

export type CreateReadingV1ReadingsPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/readings";
};

export type CreateReadingV1ReadingsPostResponses = {
  /**
   * Successful Response
   */
  201: ReadingSchema;
};

export type CreateReadingV1ReadingsPostResponse =
  CreateReadingV1ReadingsPostResponses[keyof CreateReadingV1ReadingsPostResponses];

export type GetLatestReadingV1ReadingsLatestGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/readings/latest";
};

export type GetLatestReadingV1ReadingsLatestGetResponses = {
  /**
   * Successful Response
   */
  200: ReadingSchema;
};

export type GetLatestReadingV1ReadingsLatestGetResponse =
  GetLatestReadingV1ReadingsLatestGetResponses[keyof GetLatestReadingV1ReadingsLatestGetResponses];

export type GetSocHistoryV1ReadingsSocHistoryGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Bucket width.
     */
    period?: HistoryPeriod;
  };
  url: "/v1/readings/soc-history";
};

export type GetSocHistoryV1ReadingsSocHistoryGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSocHistoryV1ReadingsSocHistoryGetError =
  GetSocHistoryV1ReadingsSocHistoryGetErrors[keyof GetSocHistoryV1ReadingsSocHistoryGetErrors];

export type GetSocHistoryV1ReadingsSocHistoryGetResponses = {
  /**
   * Successful Response
   */
  200: SocHistoryResponse;
};

export type GetSocHistoryV1ReadingsSocHistoryGetResponse =
  GetSocHistoryV1ReadingsSocHistoryGetResponses[keyof GetSocHistoryV1ReadingsSocHistoryGetResponses];

export type GetReadingV1ReadingsReadingIdGetData = {
  body?: never;
  path: {
    /**
     * Reading Id
     */
    reading_id: string;
  };
  query?: never;
  url: "/v1/readings/{reading_id}";
};

export type GetReadingV1ReadingsReadingIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetReadingV1ReadingsReadingIdGetError =
  GetReadingV1ReadingsReadingIdGetErrors[keyof GetReadingV1ReadingsReadingIdGetErrors];

export type GetReadingV1ReadingsReadingIdGetResponses = {
  /**
   * Successful Response
   */
  200: ReadingSchema;
};

export type GetReadingV1ReadingsReadingIdGetResponse =
  GetReadingV1ReadingsReadingIdGetResponses[keyof GetReadingV1ReadingsReadingIdGetResponses];
