// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen.js";
import {
  completeTaskV1TasksTaskIdCompletePost,
  createReadingV1ReadingsPost,
  createTaskV1TasksPost,
  deleteTaskV1TasksTaskIdDelete,
  getLatestReadingV1ReadingsLatestGet,
  getReadingV1ReadingsReadingIdGet,
  getTaskV1TasksTaskIdGet,
  healthzHealthzGet,
  listAreasV1TasksAreasGet,
  listReadingsV1ReadingsGet,
  listTasksV1TasksGet,
  type Options,
  reopenTaskV1TasksTaskIdReopenPost,
  reorderTasksV1TasksReorderPatch,
  updateTaskV1TasksTaskIdPatch,
} from "../sdk.gen.js";
import type {
  CompleteTaskV1TasksTaskIdCompletePostData,
  CompleteTaskV1TasksTaskIdCompletePostError,
  CompleteTaskV1TasksTaskIdCompletePostResponse,
  CreateReadingV1ReadingsPostData,
  CreateReadingV1ReadingsPostResponse,
  CreateTaskV1TasksPostData,
  CreateTaskV1TasksPostError,
  CreateTaskV1TasksPostResponse,
  DeleteTaskV1TasksTaskIdDeleteData,
  DeleteTaskV1TasksTaskIdDeleteError,
  DeleteTaskV1TasksTaskIdDeleteResponse,
  GetLatestReadingV1ReadingsLatestGetData,
  GetLatestReadingV1ReadingsLatestGetResponse,
  GetReadingV1ReadingsReadingIdGetData,
  GetReadingV1ReadingsReadingIdGetError,
  GetReadingV1ReadingsReadingIdGetResponse,
  GetTaskV1TasksTaskIdGetData,
  GetTaskV1TasksTaskIdGetError,
  GetTaskV1TasksTaskIdGetResponse,
  HealthzHealthzGetData,
  ListAreasV1TasksAreasGetData,
  ListAreasV1TasksAreasGetResponse,
  ListReadingsV1ReadingsGetData,
  ListReadingsV1ReadingsGetError,
  ListReadingsV1ReadingsGetResponse,
  ListTasksV1TasksGetData,
  ListTasksV1TasksGetError,
  ListTasksV1TasksGetResponse,
  ReopenTaskV1TasksTaskIdReopenPostData,
  ReopenTaskV1TasksTaskIdReopenPostError,
  ReopenTaskV1TasksTaskIdReopenPostResponse,
  ReorderTasksV1TasksReorderPatchData,
  ReorderTasksV1TasksReorderPatchError,
  ReorderTasksV1TasksReorderPatchResponse,
  UpdateTaskV1TasksTaskIdPatchData,
  UpdateTaskV1TasksTaskIdPatchError,
  UpdateTaskV1TasksTaskIdPatchResponse,
} from "../types.gen.js";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthzHealthzGetQueryKey = (
  options?: Options<HealthzHealthzGetData>,
) => createQueryKey("healthzHealthzGet", options);

/**
 * Healthz
 */
export const healthzHealthzGetOptions = (
  options?: Options<HealthzHealthzGetData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthzHealthzGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthzHealthzGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthzHealthzGetQueryKey(options),
  });

export const listTasksV1TasksGetQueryKey = (
  options?: Options<ListTasksV1TasksGetData>,
) => createQueryKey("listTasksV1TasksGet", options);

/**
 * List Tasks
 */
export const listTasksV1TasksGetOptions = (
  options?: Options<ListTasksV1TasksGetData>,
) =>
  queryOptions<
    ListTasksV1TasksGetResponse,
    ListTasksV1TasksGetError,
    ListTasksV1TasksGetResponse,
    ReturnType<typeof listTasksV1TasksGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTasksV1TasksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTasksV1TasksGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listTasksV1TasksGetInfiniteQueryKey = (
  options?: Options<ListTasksV1TasksGetData>,
): QueryKey<Options<ListTasksV1TasksGetData>> =>
  createQueryKey("listTasksV1TasksGet", options, true);

/**
 * List Tasks
 */
export const listTasksV1TasksGetInfiniteOptions = (
  options?: Options<ListTasksV1TasksGetData>,
) =>
  infiniteQueryOptions<
    ListTasksV1TasksGetResponse,
    ListTasksV1TasksGetError,
    InfiniteData<ListTasksV1TasksGetResponse>,
    QueryKey<Options<ListTasksV1TasksGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListTasksV1TasksGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTasksV1TasksGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listTasksV1TasksGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listTasksV1TasksGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Task
 */
export const createTaskV1TasksPostMutation = (
  options?: Partial<Options<CreateTaskV1TasksPostData>>,
): UseMutationOptions<
  CreateTaskV1TasksPostResponse,
  CreateTaskV1TasksPostError,
  Options<CreateTaskV1TasksPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTaskV1TasksPostResponse,
    CreateTaskV1TasksPostError,
    Options<CreateTaskV1TasksPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTaskV1TasksPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reorder Tasks
 */
export const reorderTasksV1TasksReorderPatchMutation = (
  options?: Partial<Options<ReorderTasksV1TasksReorderPatchData>>,
): UseMutationOptions<
  ReorderTasksV1TasksReorderPatchResponse,
  ReorderTasksV1TasksReorderPatchError,
  Options<ReorderTasksV1TasksReorderPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    ReorderTasksV1TasksReorderPatchResponse,
    ReorderTasksV1TasksReorderPatchError,
    Options<ReorderTasksV1TasksReorderPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await reorderTasksV1TasksReorderPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Task
 */
export const deleteTaskV1TasksTaskIdDeleteMutation = (
  options?: Partial<Options<DeleteTaskV1TasksTaskIdDeleteData>>,
): UseMutationOptions<
  DeleteTaskV1TasksTaskIdDeleteResponse,
  DeleteTaskV1TasksTaskIdDeleteError,
  Options<DeleteTaskV1TasksTaskIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTaskV1TasksTaskIdDeleteResponse,
    DeleteTaskV1TasksTaskIdDeleteError,
    Options<DeleteTaskV1TasksTaskIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTaskV1TasksTaskIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTaskV1TasksTaskIdGetQueryKey = (
  options: Options<GetTaskV1TasksTaskIdGetData>,
) => createQueryKey("getTaskV1TasksTaskIdGet", options);

/**
 * Get Task
 */
export const getTaskV1TasksTaskIdGetOptions = (
  options: Options<GetTaskV1TasksTaskIdGetData>,
) =>
  queryOptions<
    GetTaskV1TasksTaskIdGetResponse,
    GetTaskV1TasksTaskIdGetError,
    GetTaskV1TasksTaskIdGetResponse,
    ReturnType<typeof getTaskV1TasksTaskIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTaskV1TasksTaskIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTaskV1TasksTaskIdGetQueryKey(options),
  });

/**
 * Update Task
 */
export const updateTaskV1TasksTaskIdPatchMutation = (
  options?: Partial<Options<UpdateTaskV1TasksTaskIdPatchData>>,
): UseMutationOptions<
  UpdateTaskV1TasksTaskIdPatchResponse,
  UpdateTaskV1TasksTaskIdPatchError,
  Options<UpdateTaskV1TasksTaskIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTaskV1TasksTaskIdPatchResponse,
    UpdateTaskV1TasksTaskIdPatchError,
    Options<UpdateTaskV1TasksTaskIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTaskV1TasksTaskIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Complete Task
 */
export const completeTaskV1TasksTaskIdCompletePostMutation = (
  options?: Partial<Options<CompleteTaskV1TasksTaskIdCompletePostData>>,
): UseMutationOptions<
  CompleteTaskV1TasksTaskIdCompletePostResponse,
  CompleteTaskV1TasksTaskIdCompletePostError,
  Options<CompleteTaskV1TasksTaskIdCompletePostData>
> => {
  const mutationOptions: UseMutationOptions<
    CompleteTaskV1TasksTaskIdCompletePostResponse,
    CompleteTaskV1TasksTaskIdCompletePostError,
    Options<CompleteTaskV1TasksTaskIdCompletePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await completeTaskV1TasksTaskIdCompletePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reopen Task
 */
export const reopenTaskV1TasksTaskIdReopenPostMutation = (
  options?: Partial<Options<ReopenTaskV1TasksTaskIdReopenPostData>>,
): UseMutationOptions<
  ReopenTaskV1TasksTaskIdReopenPostResponse,
  ReopenTaskV1TasksTaskIdReopenPostError,
  Options<ReopenTaskV1TasksTaskIdReopenPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ReopenTaskV1TasksTaskIdReopenPostResponse,
    ReopenTaskV1TasksTaskIdReopenPostError,
    Options<ReopenTaskV1TasksTaskIdReopenPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await reopenTaskV1TasksTaskIdReopenPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listAreasV1TasksAreasGetQueryKey = (
  options?: Options<ListAreasV1TasksAreasGetData>,
) => createQueryKey("listAreasV1TasksAreasGet", options);

/**
 * List Areas
 */
export const listAreasV1TasksAreasGetOptions = (
  options?: Options<ListAreasV1TasksAreasGetData>,
) =>
  queryOptions<
    ListAreasV1TasksAreasGetResponse,
    DefaultError,
    ListAreasV1TasksAreasGetResponse,
    ReturnType<typeof listAreasV1TasksAreasGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAreasV1TasksAreasGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAreasV1TasksAreasGetQueryKey(options),
  });

export const listReadingsV1ReadingsGetQueryKey = (
  options?: Options<ListReadingsV1ReadingsGetData>,
) => createQueryKey("listReadingsV1ReadingsGet", options);

/**
 * List Readings
 */
export const listReadingsV1ReadingsGetOptions = (
  options?: Options<ListReadingsV1ReadingsGetData>,
) =>
  queryOptions<
    ListReadingsV1ReadingsGetResponse,
    ListReadingsV1ReadingsGetError,
    ListReadingsV1ReadingsGetResponse,
    ReturnType<typeof listReadingsV1ReadingsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listReadingsV1ReadingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listReadingsV1ReadingsGetQueryKey(options),
  });

export const listReadingsV1ReadingsGetInfiniteQueryKey = (
  options?: Options<ListReadingsV1ReadingsGetData>,
): QueryKey<Options<ListReadingsV1ReadingsGetData>> =>
  createQueryKey("listReadingsV1ReadingsGet", options, true);

/**
 * List Readings
 */
export const listReadingsV1ReadingsGetInfiniteOptions = (
  options?: Options<ListReadingsV1ReadingsGetData>,
) =>
  infiniteQueryOptions<
    ListReadingsV1ReadingsGetResponse,
    ListReadingsV1ReadingsGetError,
    InfiniteData<ListReadingsV1ReadingsGetResponse>,
    QueryKey<Options<ListReadingsV1ReadingsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListReadingsV1ReadingsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListReadingsV1ReadingsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listReadingsV1ReadingsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listReadingsV1ReadingsGetInfiniteQueryKey(options),
    },
  );

/**
 * Capture Reading
 */
export const createReadingV1ReadingsPostMutation = (
  options?: Partial<Options<CreateReadingV1ReadingsPostData>>,
): UseMutationOptions<
  CreateReadingV1ReadingsPostResponse,
  DefaultError,
  Options<CreateReadingV1ReadingsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateReadingV1ReadingsPostResponse,
    DefaultError,
    Options<CreateReadingV1ReadingsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createReadingV1ReadingsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getLatestReadingV1ReadingsLatestGetQueryKey = (
  options?: Options<GetLatestReadingV1ReadingsLatestGetData>,
) => createQueryKey("getLatestReadingV1ReadingsLatestGet", options);

/**
 * Get Latest Reading
 */
export const getLatestReadingV1ReadingsLatestGetOptions = (
  options?: Options<GetLatestReadingV1ReadingsLatestGetData>,
) =>
  queryOptions<
    GetLatestReadingV1ReadingsLatestGetResponse,
    DefaultError,
    GetLatestReadingV1ReadingsLatestGetResponse,
    ReturnType<typeof getLatestReadingV1ReadingsLatestGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLatestReadingV1ReadingsLatestGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLatestReadingV1ReadingsLatestGetQueryKey(options),
  });

export const getReadingV1ReadingsReadingIdGetQueryKey = (
  options: Options<GetReadingV1ReadingsReadingIdGetData>,
) => createQueryKey("getReadingV1ReadingsReadingIdGet", options);

/**
 * Get Reading
 */
export const getReadingV1ReadingsReadingIdGetOptions = (
  options: Options<GetReadingV1ReadingsReadingIdGetData>,
) =>
  queryOptions<
    GetReadingV1ReadingsReadingIdGetResponse,
    GetReadingV1ReadingsReadingIdGetError,
    GetReadingV1ReadingsReadingIdGetResponse,
    ReturnType<typeof getReadingV1ReadingsReadingIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getReadingV1ReadingsReadingIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getReadingV1ReadingsReadingIdGetQueryKey(options),
  });
