"""initial tasks schema

Revision ID: b22f8e48cd9a
Revises:
Create Date: 2026-07-17 18:45:43.969223

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b22f8e48cd9a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('rrule_frequency', sa.String(length=20), nullable=True),
    sa.Column('rrule_interval', sa.Integer(), nullable=True),
    sa.Column('rrule_day_of_week', sa.Integer(), nullable=True),
    sa.Column('rrule_day_of_month', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], name=op.f('tasks_parent_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey')),
  )
  op.create_index(op.f('ix_tasks_area'), 'tasks', ['area'], unique=False)
  op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
  op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
  op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
  op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
  op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
  op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
  op.drop_index(op.f('ix_tasks_area'), table_name='tasks')
  op.drop_table('tasks')
  # ### end Alembic commands ###
