"""add alarm messages to readings

Revision ID: ab501d425709
Revises: 05be12757752
Create Date: 2026-07-17 21:14:21.952784

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab501d425709'
down_revision: str | Sequence[str] | None = '05be12757752'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('readings', sa.Column('alarm_messages', sa.JSON(), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('readings', 'alarm_messages')
  # ### end Alembic commands ###
