"""add readings table

Revision ID: 05be12757752
Revises: b22f8e48cd9a
Create Date: 2026-07-17 19:17:20.225536

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05be12757752'
down_revision: str | Sequence[str] | None = 'b22f8e48cd9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'readings',
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_address', sa.String(length=100), nullable=False),
    sa.Column('device_model', sa.String(length=50), nullable=True),
    sa.Column('protocol', sa.String(length=30), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.Column('current_a', sa.Float(), nullable=False),
    sa.Column('power_w', sa.Float(), nullable=False),
    sa.Column('soc_percent', sa.Float(), nullable=False),
    sa.Column('remaining_capacity_ah', sa.Float(), nullable=False),
    sa.Column('rated_capacity_ah', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('cycles', sa.Integer(), nullable=False),
    sa.Column('cell_count', sa.Integer(), nullable=False),
    sa.Column('cell_voltage_max_v', sa.Float(), nullable=False),
    sa.Column('cell_voltage_min_v', sa.Float(), nullable=False),
    sa.Column('cell_voltage_avg_v', sa.Float(), nullable=False),
    sa.Column('cell_voltage_delta_v', sa.Float(), nullable=False),
    sa.Column('temperature_sensor_count', sa.Integer(), nullable=False),
    sa.Column('temperature_max_c', sa.Float(), nullable=False),
    sa.Column('temperature_min_c', sa.Float(), nullable=False),
    sa.Column('balancer_active', sa.Boolean(), nullable=False),
    sa.Column('charging_mosfet', sa.Boolean(), nullable=False),
    sa.Column('discharging_mosfet', sa.Boolean(), nullable=False),
    sa.Column('has_alarms', sa.Boolean(), nullable=False),
    sa.Column('cell_voltages', sa.JSON(), nullable=False),
    sa.Column('temperatures', sa.JSON(), nullable=False),
    sa.Column('balancing', sa.JSON(), nullable=True),
    sa.Column('alarms', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('readings_pkey')),
  )
  op.create_index(op.f('ix_readings_created_at'), 'readings', ['created_at'], unique=False)
  op.create_index(op.f('ix_readings_deleted_at'), 'readings', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_readings_has_alarms'), 'readings', ['has_alarms'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_readings_has_alarms'), table_name='readings')
  op.drop_index(op.f('ix_readings_deleted_at'), table_name='readings')
  op.drop_index(op.f('ix_readings_created_at'), table_name='readings')
  op.drop_table('readings')
  # ### end Alembic commands ###
